### ISSUE TITLE
Request: MotionLayout scenes support

### ISSUE THREAD

**Issue by Skyyo** [chrisbanes/insetter#43]
Would be awesome to have an ability to define insets in motion scene.

**Comment by chrisbanes** [comment]
This should already work with [InsetterConstraintHelper](https://github.com/chrisbanes/insetter/tree/master/widgets#insetterconstrainthelper)

**Comment by Skyyo** [comment]
Thanks for replying @chrisbanes .
I've created a test [project](https://github.com/Skyyo/MotionLayoutWithInsetter.git) to reproduce. Hope I just didn't understand how to use it properly with MotionLayout, because applying insets in MotionLayout in a way of adjusting [view params manually for each scene state](https://github.com/Skyyo/MotionLayoutWithInsetter/blob/5b01bc6747ad52b6834f6b357557c61aba4d41d4/app/src/main/java/com/insight/motionlayoutwithinsetter/MainActivity.kt#L27-L38) is painfull.

**Comment by chrisbanes** [comment]
@Skyyo the code in your sample looks fine. Does it work as expected?

**Comment by Skyyo** [comment]
Sadly no @chrisbanes. Both paddingSystemWindowInsets & layout_marginSystemWindowInsets

**Comment by litrik** [comment]
I have encountered the same (or similar problem). I have created a [sample project](https://github.com/litrik/sandbox-insets) that combines MotionLayout, FragmentContainerView and Insetter. Insets only get applied the very first time. After doing any kind of navigation, the insets disappear.

Note: The MotionLayout doesn't even animate anything. Clicking inside an EditText 'fixes' the insets.

If the MotionLayout is replaced by a ConstraintLayout, everything works as expected.

(Apologies if this turns out to be a different issue.)

**Comment by Skyyo** [comment]
I had a chance to ask a person related to Constraint Layout dev team about this [here](https://www.reddit.com/r/androiddev/comments/gfimrf/constraintlayout_200_beta_5/fpvyhk6/?context=3). Looks like this isn't something this library needs to deal with. @litrik

**Comment by litrik** [comment]
But why does, in my sample project, the inset get applied the very first time? Does the MotionLayout swallow all insets afterwards?

Maybe there is a way to re-execute whatever InsetterConstraintHelper is doing to fix the insets? It looks like that is what's happening when you click in an EditText... everything jumps into place.

I could not find any open Android issue for insets in a MotionLayout. Should we create one if it turns out Insetter can not fix this?

**Comment by Skyyo** [comment]
You can try @litrik, but I believe it won't get any traction really, and we won't get the expected behaviour earlier than motion layout 2.1. Also this issue can be closed since it's not related to the library.
